# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Sam Nattress
title: Writer for Sustainability Startups
email: sam@samnattress.com
website: samnattress.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: SamNattress
# github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: sam-nattress
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
  # icon: fas fa-globe
  # url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  If you're working towards greater environmental sustainability, I think your message deserves to be heard.  
  
  Your offer and the ideas behind it - no matter how complex - need to be understood. And your vision must inspire action.  
  
  That's where I come in. I bring to life in writing the ideas of sustainability startups.  
  
 
content:
  - title: Sample Client Work # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Carbon Minds
        link: https://www.carbon-minds.com/
        link_text: carbon-minds.com
        additional_links:
           - title:  Carbon Minds on LinkedIn
             # icon: fab fa-github
             url: linkedin.com/carbon-minds
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Writing with a data science startup in the chemical industry.
        description: | # this will include new lines to allow paragraphs
          <mark>Social Media</mark> I work hand in hand with the content creation team for the [Carbon Minds LinkedIn page](https://www.linkedin.com/company/carbon-minds). I contribute scripts and storylines for [videos](https://www.linkedin.com/posts/carbon-minds_explained-in-60-seconds-supplier-specific-activity-6737659043579498496-7vCt) and [PDF slide presentations](https://www.linkedin.com/posts/carbon-minds_supplier-specific-carbon-footprints-case-activity-6745303724987609088-hl8K), [content curation posts](https://www.linkedin.com/posts/carbon-minds_chemicalrecycling-bioeconomy-ccu-activity-6758342602824699904-4y-y) and [content marketing posts](https://www.linkedin.com/posts/carbon-minds_climateimpact-carbonfootprint-supplychainintelligence-activity-6755852894219644928-F39g).  
          
          <mark>Web Copy</mark> I wrote and update the copy on the [Carbon Minds website](https://www.carbon-minds.com/) in close collaboration with the startup founders.  
          
          <mark>Internal Documentation</mark> When internal documentation needs to be clear and concise, I tidy it up. 
          
          <mark>Prize Applications</mark> Carbon Minds won [a startup prize](https://www.rwth-innovation.de/en/aktuelles/aktuelle-detailseiten/winners-of-the-spin-off-award-2020) with the application we wrote.  
  - title: Other Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Writing and Teaching
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Creation and Communication
        #caption: November 2017 - Present
        quote: >
          Previous work and projects that round out my copywriting skills 
        description: | # this will include new lines to allow paragraphs
            <mark>Teaching</mark> I taught English as a foreign language for 3 years in France and 3 in Italy. Striving to eliminate the phrase "because that's just what we say" from my teaching vocabulary made me a deeper thinker, a more coherent communicator and no less of a maddeningly fastidious teacher. 
            
            <mark>Article Writing</mark> I've written content articles for sustainability startups like the world-changing [Reforestum](https://reforestum.com/how-to-choose-between-supporting-afforestation-and-forest-conservation/), scientific communities like [The Biomimicry Institute](https://biomimicry.org/the-three-seeds-of-biomimicry-every-entrepreneur-should-know-about/) and been published on sustainability startups in Medium's most subscribed publication, The Startup [here](https://medium.com/swlh/this-burgeoning-field-can-breathe-life-into-your-sustainability-startup-ca541f50a174)[, here](https://medium.com/swlh/these-startups-have-actionable-data-for-covid-climate-and-diversity-1d880edb12af) and [again here](https://medium.com/swlh/the-next-wave-of-startups-is-coming-out-of-nature-1d5061c68b24).
            
            <mark>Fiction and Poetry</mark> From scribbles that will never leave my notepad to [published works of flash fiction](https://www.thomasbrathphotography.com/1000words), I'm always spewing ink in pursuit of a good turn of phrase. 
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Cambridge
        caption: 2008 - 2012
        sub_title: BA French and Italian
        quote: >
          The place where I learnt to read and write. 
        description: | # this will include new lines to allow paragraphs
          When I think back on my time at Cambridge with the perspective of almost 10 years, I realise that the most important things I learnt had little to do with language: how to listen to the slowest speakers, who quietly opened my eyes; how to study what I loved, and leave the rest in the libraby; the joy of trying to condense a greater thinker's entire opus into a 2000 word essay; the satisfaction of finding resonance in poetry other people write off as "not as good as Baudelaire"; and how the most interesting conversations often come from music students, whose job it is listen very carefully and produce something beautiful. 
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      When I'm not writing, I might be:
      - Rock climbing
      - Volunteering at the dog shelter or fostering a homeless pup
      - Reading
      - Learning how to build things like this website
      
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
